# Generated by Django 5.1.4 on 2025-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_purchased',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
